<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcelo Silva">

<title>Teste de Hipótese para Dois Grupos com Distribuições Não Paramétricas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="teste de hipoteses ROBUSTOS para dois grupos_files/libs/clipboard/clipboard.min.js"></script>
<script src="teste de hipoteses ROBUSTOS para dois grupos_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="teste de hipoteses ROBUSTOS para dois grupos_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="teste de hipoteses ROBUSTOS para dois grupos_files/libs/quarto-html/popper.min.js"></script>
<script src="teste de hipoteses ROBUSTOS para dois grupos_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="teste de hipoteses ROBUSTOS para dois grupos_files/libs/quarto-html/anchor.min.js"></script>
<link href="teste de hipoteses ROBUSTOS para dois grupos_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="teste de hipoteses ROBUSTOS para dois grupos_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="teste de hipoteses ROBUSTOS para dois grupos_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="teste de hipoteses ROBUSTOS para dois grupos_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="teste de hipoteses ROBUSTOS para dois grupos_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Teste de Hipótese para Dois Grupos com Distribuições Não Paramétricas</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Marcelo Silva </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="parte-prática" class="level1">
<h1>Parte prática</h1>
<section id="descrição-do-conjunto-de-dados" class="level2">
<h2 class="anchored" data-anchor-id="descrição-do-conjunto-de-dados">Descrição do conjunto de dados</h2>
<p>O conjunto de dados <code>lung</code> (pulmão) contém informações de <strong>sobrevivência de pacientes com câncer de pulmão avançado</strong> do North Central Cancer Treatment Group.</p>
<section id="contexto-do-estudo" class="level3">
<h3 class="anchored" data-anchor-id="contexto-do-estudo">Contexto do estudo</h3>
<p>O foco principal deste <em>dataset</em> para o nosso estudo é avaliar se a perda de peso (wt.loss) é diferente entre homens e mulheres (sex). No dataset, a variável sex tem dois níveis: 1=Male e 2=Female. Portanto, vamos focar nessas duas informações do banco de dados.</p>
</section>
</section>
<section id="carregando-os-pacotes-necessários" class="level2">
<h2 class="anchored" data-anchor-id="carregando-os-pacotes-necessários">Carregando os pacotes necessários</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'rstatix'

The following object is masked from 'package:stats':

    filter</code></pre>
</div>
</div>
</section>
<section id="importando-e-preparando-os-dados" class="level2">
<h2 class="anchored" data-anchor-id="importando-e-preparando-os-dados">Importando e preparando os dados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>lung <span class="ot">&lt;-</span> survival<span class="sc">::</span>lung</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(lung)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  inst time status age sex ph.ecog ph.karno pat.karno meal.cal wt.loss
1    3  306      2  74   1       1       90       100     1175      NA
2    3  455      2  68   1       0       90        90     1225      15
3    3 1010      1  56   1       0       90        90       NA      15
4    5  210      2  57   1       1       90        60     1150      11
5    1  883      2  60   1       0      100        90       NA       0
6   12 1022      1  74   1       1       50        80      513       0</code></pre>
</div>
</div>
<p>Vamos checar a variável sex para ver se ela é categórica. Para isso, pergunto ao R se é um fator (is.factor). Variáveis categóricas são chamadas de fatores (factor) no R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(lung<span class="sc">$</span>sex); lung<span class="sc">$</span>sex</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 1 1 1 1 1 1 2 2 1 1 1 2 2 1 1 1 1 1 2 1 1 2 1 1 1 2 1 1 1 1 2 1 1 2 1 2 1
 [38] 2 1 2 1 2 2 2 1 2 1 1 1 2 2 1 1 1 1 1 2 1 2 2 2 1 1 2 1 1 2 2 1 1 1 2 1 1
 [75] 2 2 2 2 1 1 1 1 1 2 1 1 2 1 2 1 1 1 1 2 2 1 1 1 1 2 2 2 1 1 1 1 2 1 1 2 1
[112] 1 1 2 2 1 1 1 1 1 1 2 2 1 1 1 1 1 2 2 2 1 1 2 1 2 2 1 1 1 2 1 1 2 1 2 1 1
[149] 1 2 1 1 2 2 1 1 2 1 1 2 2 2 1 1 1 2 2 1 1 1 1 2 1 2 1 2 1 2 2 2 1 1 2 2 2
[186] 2 2 1 1 1 1 1 1 1 1 1 2 1 2 1 2 1 2 2 2 1 2 2 1 2 2 1 1 2 1 1 2 1 2 2 1 2
[223] 1 1 1 2 1 2</code></pre>
</div>
</div>
<p>Veja que ela não é uma variável categórica, mas sim uma numérica constituídas de 1 e 2. Bem, vamos rotular essa variável. Vamos chamar 1 = Male e 2 = Female. Para isso, vamos utilizar a função <code>mutate()</code> do R. E já vou aproveitar e criar o meu dataset de trabalho. Ele vai chamar <strong>ds</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ds <span class="ot">&lt;-</span> lung <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">factor</span>(sex) <span class="co"># Transformando em variável categórica</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">ifelse</span>(sex <span class="sc">==</span> <span class="dv">1</span>,<span class="st">'Male'</span>,<span class="st">'Female'</span>) <span class="co"># Criando os rótulos</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="fu">select</span>(sex, wt.loss) <span class="co"># Selecionando somente as colunas de interesse</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sex wt.loss
1 Male      NA
2 Male      15
3 Male      15
4 Male      11
5 Male       0
6 Male       0</code></pre>
</div>
</div>
<p>Os dados possuem alguns zeros e números negativos, representando pacientes que não perderam peso e ganharam peso respectivamente. Não iremos trabalhar com esses pacientes. Portanto, vou criar um filtro para que o R exclua esses pacientes</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ds <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(wt.loss <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Agora, vamos ver se tem algum valor NA (Not annoted ou valores faltantes).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>naniar<span class="sc">::</span> <span class="fu">miss_var_summary</span>(ds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  variable n_miss pct_miss
  &lt;chr&gt;     &lt;int&gt;    &lt;num&gt;
1 sex           0        0
2 wt.loss       0        0</code></pre>
</div>
</div>
<p>Observe que wt.loss tem 14 valores faltantes. Não faz sentido deixá-lo no banco de dados. Portanto, vamos trabalhar somente com <strong>casos completos</strong>, utilizando o filtro <code>complete.cases</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>ds <span class="ot">&lt;-</span> ds <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">complete.cases</span>(wt.loss))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>naniar<span class="sc">::</span> <span class="fu">miss_var_summary</span>(ds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  variable n_miss pct_miss
  &lt;chr&gt;     &lt;int&gt;    &lt;num&gt;
1 sex           0        0
2 wt.loss       0        0</code></pre>
</div>
</div>
<p>Vejam que todos os valores faltantes foram removidos do estudo.</p>
</section>
<section id="análise-dos-parâmetros-estatísticos" class="level2">
<h2 class="anchored" data-anchor-id="análise-dos-parâmetros-estatísticos">Análise dos parâmetros estatísticos</h2>
<p>Vamos analisar os parâmetros básicos de cada um dos grupos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ds <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span> <span class="fu">get_summary_stats</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 14
  sex    variable     n   min   max median    q1    q3   iqr   mad  mean    sd
  &lt;chr&gt;  &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Female wt.loss     57     1    52     10     4  17    13    8.90  13.3  12.4
2 Male   wt.loss     96     1    68     14     7  20.5  13.5 10.4   15.6  12.0
# ℹ 2 more variables: se &lt;dbl&gt;, ci &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Observamos que a diferença de médias entre os grupos é próximo de dois quilos. Podemos ver que mediana e média são diferentes, sugerindo assimetria. Vamos ver o boxplot dos dados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>ds <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(sex,wt.loss)) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="teste-de-hipoteses-ROBUSTOS-para-dois-grupos_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O boxplot nos mostra que, a distribuição dos dados dentro de cada grupo é semelhante (tamanho das caixas). Vimos que os dois grupos possuem outliers (pontos pretos no gráfico). Vamos ver quem são.</p>
</section>
<section id="identificação-dos-outliers" class="level2">
<h2 class="anchored" data-anchor-id="identificação-dos-outliers">Identificação dos outliers</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ds <span class="sc">%&gt;%</span> <span class="fu">identify_outliers</span>(wt.loss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       sex wt.loss is.outlier is.extreme
15    Male      60       TRUE      FALSE
62    Male      68       TRUE       TRUE
131 Female      52       TRUE      FALSE
134 Female      49       TRUE      FALSE</code></pre>
</div>
</div>
<p>Os outliers não são erro de anotação. São simplismente pessoas que perderam mais peso. Portanto vou mantê-los.</p>
<p>Vamos ver o qqplot para vermos os desvios de normalidade.</p>
</section>
<section id="investigação-do-tipo-de-distribuição" class="level2">
<h2 class="anchored" data-anchor-id="investigação-do-tipo-de-distribuição">Investigação do tipo de distribuição</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>ds <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> wt.loss)) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="teste-de-hipoteses-ROBUSTOS-para-dois-grupos_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Veja como tem pontos que se afastam da reta nas pontas. Isso sugere caudas pesadas (valores extremos), como observamos nos dados. Vamos ver o que o teste de normalidade Shapiro Wilk nos diz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>ds <span class="sc">%&gt;%</span> <span class="fu">shapiro_test</span>(wt.loss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  variable statistic        p
  &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;
1 wt.loss      0.873 4.07e-10</code></pre>
</div>
</div>
<p>Vejam que o p do teste de normalidade é muito menor do que 0.05, indicando que não tenho informações suficientes para afirmar que a distribuição é normal, e portanto eu assumo a hipótese alternativa do teste de normalidade (a distribuição não é normal).</p>
</section>
<section id="realização-do-teste-robusto-yen" class="level2">
<h2 class="anchored" data-anchor-id="realização-do-teste-robusto-yen">Realização do teste robusto (Yen)</h2>
<p>Esse teste traz várias vantagens:</p>
<ol type="1">
<li><p>Robustez: menos sensíveis a <em>outliers</em>.</p></li>
<li><p>Precisão: uso de bootstrap melhora a estimativa do p-valor e intervalo de confiança, especialmente em amostras pequenas e amostras assimétricas (com <em>outliers</em>).</p></li>
<li><p>Flexibilidade: não assumem normalidade ou homogeneidade de variâncias.</p></li>
</ol>
<p>Portanto, vamos chamar o pacote <code>WRS2</code> que contém a função <code>yuenbt()</code>. Os arugmentoos est = ‘median’ diz à função para usar como estimador a mediana, por causa da assimetria dos dados. O nboot é o número de vezes que ele realocará as amostras para adiquirir um intervalo de confiança da diferença das medianas mais robusto.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>teste_robusto <span class="ot">&lt;-</span> WRS2<span class="sc">::</span><span class="fu">yuenbt</span>(wt.loss<span class="sc">~</span>sex, <span class="at">data =</span> ds, <span class="at">est =</span> <span class="st">'median'</span>, <span class="at">nboot =</span> <span class="dv">2000</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>teste_robusto</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
WRS2::yuenbt(formula = wt.loss ~ sex, data = ds, nboot = 2000, 
    est = "median")

Test statistic: -1.7533 (df = NA), p-value = 0.076

Trimmed mean difference:  -3.63793 
95 percent confidence interval:
-7.6914     0.4156 </code></pre>
</div>
</div>
<p>Observe que o valor de p-value foi de 0.076 , maior do que 0.05, marginando a diferença estatística. Além disso, podemos observar que o intervalo de confiança foi de -7.691423, 0.4155609, incluindo o zero afirmando que a diferença não foi estatisticamente significativa.</p>
</section>
</section>
<section id="tamanho-de-efeito-robusto-akp" class="level1">
<h1>Tamanho de efeito robusto (akp)</h1>
<p>Podemos avaliar o tamanho do efeito. Para isso, vamos utilizar a função <code>apk.effect</code> também do pacote <code>WRS2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>efeito_robusto <span class="ot">&lt;-</span> WRS2<span class="sc">::</span><span class="fu">akp.effect</span>(wt.loss<span class="sc">~</span>sex, <span class="at">data =</span> ds, <span class="at">EQVAR =</span> F, <span class="at">nboot =</span> <span class="dv">2000</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>efeito_robusto</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$AKPeffect
[1] -0.3101211

$AKPci
[1] -0.95681580  0.03483678

$alpha
[1] 0.05

$call
WRS2::akp.effect(formula = wt.loss ~ sex, data = ds, EQVAR = F, 
    nboot = 2000)

attr(,"class")
[1] "AKP"</code></pre>
</div>
</div>
<p>O efeito encontrado foi considerado fraco -0.3101211 com um valor de intervalo de confiança de -0.9568158, 0.0348368. O tamanho do efeito nos ajuda a intepretar o valor marginal de P. E, portanto, podemos afirmar que não há diferença na perda de peso entre os sexos masculinos e femininos.</p>
<section id="descrição-dos-métodos-e-resultados" class="level2">
<h2 class="anchored" data-anchor-id="descrição-dos-métodos-e-resultados">Descrição dos métodos e resultados</h2>
<section id="descrição-do-método-de-análise" class="level3">
<h3 class="anchored" data-anchor-id="descrição-do-método-de-análise">Descrição do método de análise</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para comparar a perda de peso entre os sexos, levando em consideração a <strong>assimetria</strong> na distribuição dos dados, utilizamos o <strong>teste de Yuen para médias aparadas</strong> (<code>yuenbt()</code>), implementado no pacote <code>WRS2</code> do R. Esse teste é uma alternativa robusta aos testes <em>t</em> tradicionais, sendo especialmente adequado para dados com <strong>distribuições não normais</strong> ou <strong>variâncias desiguais</strong>.</p>
<p>Para avaliar a magnitude da diferença, calculamos o <strong>tamanho de efeito robusto</strong> usando a função <code>akp.effect()</code> do pacote <code>WRS2</code>, com <code>EQVAR = FALSE</code> (assumindo variâncias desiguais entre os grupos) e o mesmo número de reamostragem (<em>n</em> = 2000).</p>
</div>
</div>
</section>
<section id="descrição-dos-resultados" class="level3">
<h3 class="anchored" data-anchor-id="descrição-dos-resultados">Descrição dos resultados</h3>
<p>Para a descrição dos resultados, temos que mencionar as diferenças entre as médias aparadas, uma vez que foi isso utilizado pelo teste, o seu intervalo de confiança, o valor de P. Além disso, o tamanho de efeito e seu intervalo de confiança.</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Os resultados indicam que a diferença entre as medianas observadas não pode ser atribuída ao sexo masculino ou feminino (diff = -3.64, IC95% [-7.69, 0.42]; p = 0.08. O tamanho de efeito observado foi moderado (-0.31 , IC95% [-0.96, 0.03]</p>
</div>
</div>
</div>
<p>Se tivéssemos utilizado o teste t e o cohen’s d, qual seria o resultado. Vamos ver</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(wt.loss<span class="sc">~</span>sex, <span class="at">data =</span> ds, <span class="at">var.equal =</span> F) ; effectsize<span class="sc">::</span><span class="fu">cohens_d</span>(wt.loss<span class="sc">~</span>sex, <span class="at">data =</span> ds, <span class="at">var.equal =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  wt.loss by sex
t = -1.1438, df = 114.2, p-value = 0.2551
alternative hypothesis: true difference in means between group Female and group Male is not equal to 0
95 percent confidence interval:
 -6.404335  1.715739
sample estimates:
mean in group Female   mean in group Male 
             13.2807              15.6250 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |        95% CI
-------------------------
-0.19     | [-0.52, 0.14]

- Estimated using un-pooled SD.</code></pre>
</div>
</div>
<p>Observe que o valor de p ficou bem mais alto (0.25), be diferente do valor de p do teste robusto. Além disso, o valor do Cohen’s d ficou bem mais baixo (-0.19).</p>
</section>
</section>
</section>
<section id="parte-teórica" class="level1">
<h1>Parte teórica</h1>
<section id="o-desafio-da-não-normalidade-e-assimetria" class="level2">
<h2 class="anchored" data-anchor-id="o-desafio-da-não-normalidade-e-assimetria">O desafio da não-normalidade e assimetria</h2>
<p>Os testes paramétricos, como o Teste <em>t</em> de Student, baseiam-se em pressupostos rígidos, sendo o mais conhecido a <strong>normalidade da distribuição</strong> dos dados (ou das diferenças). Quando os dados apresentam <strong>assimetria</strong> acentuada, têm distribuições incomuns ou contêm <em>outliers</em> influentes, a validade dos resultados de um teste paramétrico é comprometida, podendo levar a conclusões erradas.</p>
<p>Tradicionalmente, a solução seria o uso de testes não paramétricos baseados em postos (<em>ranks</em>), como o Teste <em>U</em> de Mann-Whitney. No entanto, esses testes <strong>transformam os dados em postos</strong>, alterando a natureza da informação e limitando a interpretação das diferenças em termos de médias originais.</p>
</section>
<section id="a-abordagem-robusta" class="level2">
<h2 class="anchored" data-anchor-id="a-abordagem-robusta">A abordagem robusta</h2>
<p>Uma alternativa moderna e preferível é o uso de <strong>testes robustos</strong>, que são menos sensíveis às violações dos pressupostos de normalidade e homogeneidade de variância, sem a necessidade de transformar os dados. Esses testes geralmente se concentram em comparar <strong>medidas de tendência central mais resistentes</strong> à assimetria, como a <strong>mediana</strong> ou a <strong>média aparada</strong> (<em>trimmed mean</em>).</p>
<section id="testes-robustos-baseados-em-média-aparada-teste-de-yen" class="level3">
<h3 class="anchored" data-anchor-id="testes-robustos-baseados-em-média-aparada-teste-de-yen">Testes robustos baseados em média aparada (Teste de Yen)</h3>
<p>O <strong>Teste de Yen (ou Teste <em>t</em></strong> de Yen) é um exemplo de teste robusto. Em vez de usar a média aritmética tradicional, ele utiliza a <strong>média aparada</strong> (comumente a 10% ou 20%). A média aparada é calculada após a remoção de uma porcentagem igual dos valores mais extremos (os maiores e os menores) de cada cauda da distribuição.</p>
<ul>
<li><p><strong>Vantagem:</strong> ao descartar os valores extremos, a média aparada se torna muito mais resistente à influência de <em>outliers</em> e à assimetria, fornecendo uma estimativa mais representativa do centro da distribuição em dados não normais. O Teste de Yen então compara essas médias aparadas, sendo uma alternativa poderosa e mais precisa que o <strong><em>t</em></strong> de Student nesses cenários.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Na execução do teste de Yen, os <em>outliers</em> não são removidos do banco de dados.</p>
</div>
</div></li>
</ul>
</section>
<section id="testes-robustos-de-reamostragem-bootstrap" class="level3">
<h3 class="anchored" data-anchor-id="testes-robustos-de-reamostragem-bootstrap">Testes robustos de reamostragem (Bootstrap)</h3>
<p>O <strong>Bootstrap</strong> é uma técnica de reamostragem não paramétrica extremamente poderosa que não assume nenhuma forma específica de distribuição (como a normal).</p>
<ul>
<li><p><strong>Funcionamento:</strong> em vez de depender de fórmulas teóricas, o <em>bootstrap</em> cria milhares de novas amostras (<em>bootstrap samples</em>) a partir da amostra original, amostrando com reposição.</p></li>
<li><p><strong>Aplicação em teste de hipótese:</strong> o <em>bootstrap</em> é usado para estimar as estatísticas de interesse (como a diferença entre as médias ou medianas) e seus intervalos de confiança, oferecendo um <strong>intervalo de confiança</strong> para a diferença de médias que é mais preciso e robusto em amostras não normais. Se o intervalo de confiança dessa diferença incluir zero, a diferença não é considerada estatisticamente significativa.</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Exemplos de Intervalos de cConfiança (IC 95%) para a diferença de médias</strong>:</p>
<ol type="1">
<li><p><strong>IC 95% =</strong> [−3.5&nbsp;a&nbsp;1.2]: neste caso, o zero (0) está incluído no intervalo. A conclusão é que <strong>não há diferença significativa</strong> entre os grupos.</p></li>
<li><p><strong>IC 95% =</strong> [0.8&nbsp;a&nbsp;4.1]: neste caso, o zero (0) <em>não</em> está incluído. A conclusão é que <strong>há uma diferença significativa</strong>, e a média do primeiro grupo (μ1​) é maior que a do segundo.</p></li>
<li><p><strong>IC 95% =</strong> [−5.0&nbsp;a&nbsp;−1.9]: neste caso, o zero (0) <em>não</em> está incluído. A conclusão é que <strong>há uma diferença significativa</strong>, e a média do primeiro grupo (μ1​) é menor que a do segundo.</p></li>
</ol>
</div>
</div>
</section>
<section id="a-importância-do-tamanho-do-efeito" class="level3">
<h3 class="anchored" data-anchor-id="a-importância-do-tamanho-do-efeito">A importância do tamanho do efeito</h3>
<p>Ao lidar com distribuições não normais e especialmente com o uso de testes robustos, o <strong>tamanho do efeito</strong> torna-se ainda mais crucial.</p>
<p>O p-valor apenas informa se a diferença observada é <strong>estatisticamente significativa</strong> (se é improvável ter ocorrido por acaso), mas não diz nada sobre a sua <strong>magnitude</strong> ou <strong>relevância prática</strong>. O tamanho do efeito preenche essa lacuna.</p>
<ul>
<li><p><strong>Objetivo:</strong> quantificar a <strong>magnitude da diferença</strong> entre os grupos em uma escala padronizada, permitindo que a diferença seja interpretada independentemente do tamanho da amostra.</p></li>
<li><p><strong>Medidas robustas:</strong> para comparações de grupos não normais, é preferível utilizar medidas de tamanho do efeito que são robustas à assimetria. O <strong>Hedges’g</strong> é uma escolha popular, pois aplica uma correção para o viés em amostras pequenas, sendo mais preciso que o Cohen’s d.&nbsp;Alternativamente, podem ser utilizados tamanhos de efeito baseados em <strong>percentis ou <em>rankings</em></strong>, que são menos sensíveis à forma da distribuição.</p></li>
</ul>
<p>No ambiente de programação <strong>R</strong>, existem pacotes dedicados que facilitam o cálculo de tamanhos de efeito robustos, indo além dos métodos tradicionais. O pacote <code>effectsize</code> é amplamente utilizado e permite calcular o <strong>Hedges’g</strong> e outras medidas.</p>
<p>Além disso, quando se utiliza o <strong>Bootstrap</strong> ou se compara medidas centrais robustas (como a média aparada), o pacote <strong><code>WRS2</code></strong> (ou <em>Robust Statistical Methods</em>) é a ferramenta ideal. Ele oferece funções para calcular o <strong>tamanho do efeito robusto</strong> diretamente, como a diferença padronizada entre as médias aparadas, que é a medida mais apropriada para acompanhar o Teste de Yen. Isso garante que a métrica de magnitude utilizada esteja alinhada com a medida de tendência central robusta empregada no teste de hipótese.</p>
<p>Em resumo, a combinação de testes robustos (como o Teste de Yen ou a análise <em>bootstrap</em>) com uma interpretação obrigatória do <strong>tamanho do efeito</strong> oferece uma metodologia estatística completa e confiável para comparar dois grupos quando os pressupostos paramétricos são violados.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>